# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  "test":
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run: go test -v ./...
  "lint":
    docker:
      - image: golangci/golangci-lint:v1.15
    steps:
      - checkout
      - run: go mod download
      - run: golangci-lint run
  "codecov":
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: ./.circleci/testcover.sh
      - run: bash <(curl -s https://codecov.io/bash)
  "e2e":
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -tags e2e ./e2e/...

workflows:
  version: 2
  test-and-lint:
    jobs:
      - "test"
      - "lint"
      - "codecov"
      - "e2e"
